# build stage
FROM golang:alpine AS build-env
ADD . /src
RUN cd /src/cmd/bench && go get ./... & go build

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/cmd/bench/bench /app/
ENTRYPOINT ./bench